<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * ISO 3166-1 alpha-2 codes with Hungarian names (via PHP intl / ICU data),
     * sorted with Magyarország first, then alphabetically by Hungarian collation.
     * Excludes uninhabited territories (Antarctica and similar) that aren't
     * realistic shipping destinations.
     */
    public function run(): void
    {
        $countries = [
            ["name" => "Magyarország", "code" => "HU", "sort_order" => 0],
            ["name" => "Afganisztán", "code" => "AF", "sort_order" => 1],
            ["name" => "Åland-szigetek", "code" => "AX", "sort_order" => 2],
            ["name" => "Albánia", "code" => "AL", "sort_order" => 3],
            ["name" => "Algéria", "code" => "DZ", "sort_order" => 4],
            ["name" => "Amerikai Szamoa", "code" => "AS", "sort_order" => 5],
            ["name" => "Amerikai Virgin-szigetek", "code" => "VI", "sort_order" => 6],
            ["name" => "Andorra", "code" => "AD", "sort_order" => 7],
            ["name" => "Angola", "code" => "AO", "sort_order" => 8],
            ["name" => "Anguilla", "code" => "AI", "sort_order" => 9],
            ["name" => "Antigua és Barbuda", "code" => "AG", "sort_order" => 10],
            ["name" => "Argentína", "code" => "AR", "sort_order" => 11],
            ["name" => "Aruba", "code" => "AW", "sort_order" => 12],
            ["name" => "Ausztrália", "code" => "AU", "sort_order" => 13],
            ["name" => "Ausztria", "code" => "AT", "sort_order" => 14],
            ["name" => "Azerbajdzsán", "code" => "AZ", "sort_order" => 15],
            ["name" => "Bahama-szigetek", "code" => "BS", "sort_order" => 16],
            ["name" => "Bahrein", "code" => "BH", "sort_order" => 17],
            ["name" => "Banglades", "code" => "BD", "sort_order" => 18],
            ["name" => "Barbados", "code" => "BB", "sort_order" => 19],
            ["name" => "Belarusz", "code" => "BY", "sort_order" => 20],
            ["name" => "Belgium", "code" => "BE", "sort_order" => 21],
            ["name" => "Belize", "code" => "BZ", "sort_order" => 22],
            ["name" => "Benin", "code" => "BJ", "sort_order" => 23],
            ["name" => "Bermuda", "code" => "BM", "sort_order" => 24],
            ["name" => "Bhután", "code" => "BT", "sort_order" => 25],
            ["name" => "Bissau-Guinea", "code" => "GW", "sort_order" => 26],
            ["name" => "Bolívia", "code" => "BO", "sort_order" => 27],
            ["name" => "Bosznia-Hercegovina", "code" => "BA", "sort_order" => 28],
            ["name" => "Botswana", "code" => "BW", "sort_order" => 29],
            ["name" => "Brazília", "code" => "BR", "sort_order" => 30],
            ["name" => "Brit Virgin-szigetek", "code" => "VG", "sort_order" => 31],
            ["name" => "Brunei", "code" => "BN", "sort_order" => 32],
            ["name" => "Bulgária", "code" => "BG", "sort_order" => 33],
            ["name" => "Burkina Faso", "code" => "BF", "sort_order" => 34],
            ["name" => "Burundi", "code" => "BI", "sort_order" => 35],
            ["name" => "Chile", "code" => "CL", "sort_order" => 36],
            ["name" => "Ciprus", "code" => "CY", "sort_order" => 37],
            ["name" => "Comore-szigetek", "code" => "KM", "sort_order" => 38],
            ["name" => "Cook-szigetek", "code" => "CK", "sort_order" => 39],
            ["name" => "Costa Rica", "code" => "CR", "sort_order" => 40],
            ["name" => "Curaçao", "code" => "CW", "sort_order" => 41],
            ["name" => "Csád", "code" => "TD", "sort_order" => 42],
            ["name" => "Csehország", "code" => "CZ", "sort_order" => 43],
            ["name" => "Dánia", "code" => "DK", "sort_order" => 44],
            ["name" => "Dél-afrikai Köztársaság", "code" => "ZA", "sort_order" => 45],
            ["name" => "Dél-Korea", "code" => "KR", "sort_order" => 46],
            ["name" => "Dél-Szudán", "code" => "SS", "sort_order" => 47],
            ["name" => "Dominika", "code" => "DM", "sort_order" => 48],
            ["name" => "Dominikai Köztársaság", "code" => "DO", "sort_order" => 49],
            ["name" => "Dzsibuti", "code" => "DJ", "sort_order" => 50],
            ["name" => "Ecuador", "code" => "EC", "sort_order" => 51],
            ["name" => "Egyenlítői-Guinea", "code" => "GQ", "sort_order" => 52],
            ["name" => "Egyesült Államok", "code" => "US", "sort_order" => 53],
            ["name" => "Egyesült Arab Emírségek", "code" => "AE", "sort_order" => 54],
            ["name" => "Egyesült Királyság", "code" => "GB", "sort_order" => 55],
            ["name" => "Egyiptom", "code" => "EG", "sort_order" => 56],
            ["name" => "Elefántcsontpart", "code" => "CI", "sort_order" => 57],
            ["name" => "Eritrea", "code" => "ER", "sort_order" => 58],
            ["name" => "Észak-Korea", "code" => "KP", "sort_order" => 59],
            ["name" => "Észak-Macedónia", "code" => "MK", "sort_order" => 60],
            ["name" => "Északi Mariana-szigetek", "code" => "MP", "sort_order" => 61],
            ["name" => "Észtország", "code" => "EE", "sort_order" => 62],
            ["name" => "Etiópia", "code" => "ET", "sort_order" => 63],
            ["name" => "Falkland-szigetek", "code" => "FK", "sort_order" => 64],
            ["name" => "Feröer szigetek", "code" => "FO", "sort_order" => 65],
            ["name" => "Fidzsi", "code" => "FJ", "sort_order" => 66],
            ["name" => "Finnország", "code" => "FI", "sort_order" => 67],
            ["name" => "Francia Guyana", "code" => "GF", "sort_order" => 68],
            ["name" => "Francia Polinézia", "code" => "PF", "sort_order" => 69],
            ["name" => "Franciaország", "code" => "FR", "sort_order" => 70],
            ["name" => "Fülöp-szigetek", "code" => "PH", "sort_order" => 71],
            ["name" => "Gabon", "code" => "GA", "sort_order" => 72],
            ["name" => "Gambia", "code" => "GM", "sort_order" => 73],
            ["name" => "Ghána", "code" => "GH", "sort_order" => 74],
            ["name" => "Gibraltár", "code" => "GI", "sort_order" => 75],
            ["name" => "Görögország", "code" => "GR", "sort_order" => 76],
            ["name" => "Grenada", "code" => "GD", "sort_order" => 77],
            ["name" => "Grönland", "code" => "GL", "sort_order" => 78],
            ["name" => "Grúzia", "code" => "GE", "sort_order" => 79],
            ["name" => "Guadeloupe", "code" => "GP", "sort_order" => 80],
            ["name" => "Guam", "code" => "GU", "sort_order" => 81],
            ["name" => "Guatemala", "code" => "GT", "sort_order" => 82],
            ["name" => "Guernsey", "code" => "GG", "sort_order" => 83],
            ["name" => "Guinea", "code" => "GN", "sort_order" => 84],
            ["name" => "Guyana", "code" => "GY", "sort_order" => 85],
            ["name" => "Haiti", "code" => "HT", "sort_order" => 86],
            ["name" => "Holland Karib-térség", "code" => "BQ", "sort_order" => 87],
            ["name" => "Hollandia", "code" => "NL", "sort_order" => 88],
            ["name" => "Honduras", "code" => "HN", "sort_order" => 89],
            ["name" => "Hongkong KKT", "code" => "HK", "sort_order" => 90],
            ["name" => "Horvátország", "code" => "HR", "sort_order" => 91],
            ["name" => "India", "code" => "IN", "sort_order" => 92],
            ["name" => "Indonézia", "code" => "ID", "sort_order" => 93],
            ["name" => "Irak", "code" => "IQ", "sort_order" => 94],
            ["name" => "Irán", "code" => "IR", "sort_order" => 95],
            ["name" => "Írország", "code" => "IE", "sort_order" => 96],
            ["name" => "Izland", "code" => "IS", "sort_order" => 97],
            ["name" => "Izrael", "code" => "IL", "sort_order" => 98],
            ["name" => "Jamaica", "code" => "JM", "sort_order" => 99],
            ["name" => "Japán", "code" => "JP", "sort_order" => 100],
            ["name" => "Jemen", "code" => "YE", "sort_order" => 101],
            ["name" => "Jersey", "code" => "JE", "sort_order" => 102],
            ["name" => "Jordánia", "code" => "JO", "sort_order" => 103],
            ["name" => "Kajmán-szigetek", "code" => "KY", "sort_order" => 104],
            ["name" => "Kambodzsa", "code" => "KH", "sort_order" => 105],
            ["name" => "Kamerun", "code" => "CM", "sort_order" => 106],
            ["name" => "Kanada", "code" => "CA", "sort_order" => 107],
            ["name" => "Karácsony-sziget", "code" => "CX", "sort_order" => 108],
            ["name" => "Katar", "code" => "QA", "sort_order" => 109],
            ["name" => "Kazahsztán", "code" => "KZ", "sort_order" => 110],
            ["name" => "Kelet-Timor", "code" => "TL", "sort_order" => 111],
            ["name" => "Kenya", "code" => "KE", "sort_order" => 112],
            ["name" => "Kína", "code" => "CN", "sort_order" => 113],
            ["name" => "Kirgizisztán", "code" => "KG", "sort_order" => 114],
            ["name" => "Kiribati", "code" => "KI", "sort_order" => 115],
            ["name" => "Kókusz (Keeling)-szigetek", "code" => "CC", "sort_order" => 116],
            ["name" => "Kolumbia", "code" => "CO", "sort_order" => 117],
            ["name" => "Kongó – Brazzaville", "code" => "CG", "sort_order" => 118],
            ["name" => "Kongó – Kinshasa", "code" => "CD", "sort_order" => 119],
            ["name" => "Közép-afrikai Köztársaság", "code" => "CF", "sort_order" => 120],
            ["name" => "Kuba", "code" => "CU", "sort_order" => 121],
            ["name" => "Kuvait", "code" => "KW", "sort_order" => 122],
            ["name" => "Laosz", "code" => "LA", "sort_order" => 123],
            ["name" => "Lengyelország", "code" => "PL", "sort_order" => 124],
            ["name" => "Lesotho", "code" => "LS", "sort_order" => 125],
            ["name" => "Lettország", "code" => "LV", "sort_order" => 126],
            ["name" => "Libanon", "code" => "LB", "sort_order" => 127],
            ["name" => "Libéria", "code" => "LR", "sort_order" => 128],
            ["name" => "Líbia", "code" => "LY", "sort_order" => 129],
            ["name" => "Liechtenstein", "code" => "LI", "sort_order" => 130],
            ["name" => "Litvánia", "code" => "LT", "sort_order" => 131],
            ["name" => "Luxemburg", "code" => "LU", "sort_order" => 132],
            ["name" => "Madagaszkár", "code" => "MG", "sort_order" => 133],
            ["name" => "Makaó KKT", "code" => "MO", "sort_order" => 134],
            ["name" => "Malajzia", "code" => "MY", "sort_order" => 135],
            ["name" => "Malawi", "code" => "MW", "sort_order" => 136],
            ["name" => "Maldív-szigetek", "code" => "MV", "sort_order" => 137],
            ["name" => "Mali", "code" => "ML", "sort_order" => 138],
            ["name" => "Málta", "code" => "MT", "sort_order" => 139],
            ["name" => "Man-sziget", "code" => "IM", "sort_order" => 140],
            ["name" => "Marokkó", "code" => "MA", "sort_order" => 141],
            ["name" => "Marshall-szigetek", "code" => "MH", "sort_order" => 142],
            ["name" => "Martinique", "code" => "MQ", "sort_order" => 143],
            ["name" => "Mauritánia", "code" => "MR", "sort_order" => 144],
            ["name" => "Mauritius", "code" => "MU", "sort_order" => 145],
            ["name" => "Mayotte", "code" => "YT", "sort_order" => 146],
            ["name" => "Mexikó", "code" => "MX", "sort_order" => 147],
            ["name" => "Mianmar", "code" => "MM", "sort_order" => 148],
            ["name" => "Mikronézia", "code" => "FM", "sort_order" => 149],
            ["name" => "Moldova", "code" => "MD", "sort_order" => 150],
            ["name" => "Monaco", "code" => "MC", "sort_order" => 151],
            ["name" => "Mongólia", "code" => "MN", "sort_order" => 152],
            ["name" => "Montenegró", "code" => "ME", "sort_order" => 153],
            ["name" => "Montserrat", "code" => "MS", "sort_order" => 154],
            ["name" => "Mozambik", "code" => "MZ", "sort_order" => 155],
            ["name" => "Namíbia", "code" => "NA", "sort_order" => 156],
            ["name" => "Nauru", "code" => "NR", "sort_order" => 157],
            ["name" => "Németország", "code" => "DE", "sort_order" => 158],
            ["name" => "Nepál", "code" => "NP", "sort_order" => 159],
            ["name" => "Nicaragua", "code" => "NI", "sort_order" => 160],
            ["name" => "Niger", "code" => "NE", "sort_order" => 161],
            ["name" => "Nigéria", "code" => "NG", "sort_order" => 162],
            ["name" => "Niue", "code" => "NU", "sort_order" => 163],
            ["name" => "Norfolk-sziget", "code" => "NF", "sort_order" => 164],
            ["name" => "Norvégia", "code" => "NO", "sort_order" => 165],
            ["name" => "Nyugat-Szahara", "code" => "EH", "sort_order" => 166],
            ["name" => "Olaszország", "code" => "IT", "sort_order" => 167],
            ["name" => "Omán", "code" => "OM", "sort_order" => 168],
            ["name" => "Oroszország", "code" => "RU", "sort_order" => 169],
            ["name" => "Örményország", "code" => "AM", "sort_order" => 170],
            ["name" => "Pakisztán", "code" => "PK", "sort_order" => 171],
            ["name" => "Palau", "code" => "PW", "sort_order" => 172],
            ["name" => "Palesztin Autonómia", "code" => "PS", "sort_order" => 173],
            ["name" => "Panama", "code" => "PA", "sort_order" => 174],
            ["name" => "Pápua Új-Guinea", "code" => "PG", "sort_order" => 175],
            ["name" => "Paraguay", "code" => "PY", "sort_order" => 176],
            ["name" => "Peru", "code" => "PE", "sort_order" => 177],
            ["name" => "Pitcairn-szigetek", "code" => "PN", "sort_order" => 178],
            ["name" => "Portugália", "code" => "PT", "sort_order" => 179],
            ["name" => "Puerto Rico", "code" => "PR", "sort_order" => 180],
            ["name" => "Réunion", "code" => "RE", "sort_order" => 181],
            ["name" => "Románia", "code" => "RO", "sort_order" => 182],
            ["name" => "Ruanda", "code" => "RW", "sort_order" => 183],
            ["name" => "Saint Kitts és Nevis", "code" => "KN", "sort_order" => 184],
            ["name" => "Saint Lucia", "code" => "LC", "sort_order" => 185],
            ["name" => "Saint Martin", "code" => "MF", "sort_order" => 186],
            ["name" => "Saint Vincent és a Grenadine-szigetek", "code" => "VC", "sort_order" => 187],
            ["name" => "Saint-Barthélemy", "code" => "BL", "sort_order" => 188],
            ["name" => "Saint-Pierre és Miquelon", "code" => "PM", "sort_order" => 189],
            ["name" => "Salamon-szigetek", "code" => "SB", "sort_order" => 190],
            ["name" => "Salvador", "code" => "SV", "sort_order" => 191],
            ["name" => "San Marino", "code" => "SM", "sort_order" => 192],
            ["name" => "São Tomé és Príncipe", "code" => "ST", "sort_order" => 193],
            ["name" => "Seychelle-szigetek", "code" => "SC", "sort_order" => 194],
            ["name" => "Sierra Leone", "code" => "SL", "sort_order" => 195],
            ["name" => "Sint Maarten", "code" => "SX", "sort_order" => 196],
            ["name" => "Spanyolország", "code" => "ES", "sort_order" => 197],
            ["name" => "Srí Lanka", "code" => "LK", "sort_order" => 198],
            ["name" => "Suriname", "code" => "SR", "sort_order" => 199],
            ["name" => "Svájc", "code" => "CH", "sort_order" => 200],
            ["name" => "Svalbard és Jan Mayen", "code" => "SJ", "sort_order" => 201],
            ["name" => "Svédország", "code" => "SE", "sort_order" => 202],
            ["name" => "Szamoa", "code" => "WS", "sort_order" => 203],
            ["name" => "Szaúd-Arábia", "code" => "SA", "sort_order" => 204],
            ["name" => "Szenegál", "code" => "SN", "sort_order" => 205],
            ["name" => "Szent Ilona", "code" => "SH", "sort_order" => 206],
            ["name" => "Szerbia", "code" => "RS", "sort_order" => 207],
            ["name" => "Szingapúr", "code" => "SG", "sort_order" => 208],
            ["name" => "Szíria", "code" => "SY", "sort_order" => 209],
            ["name" => "Szlovákia", "code" => "SK", "sort_order" => 210],
            ["name" => "Szlovénia", "code" => "SI", "sort_order" => 211],
            ["name" => "Szomália", "code" => "SO", "sort_order" => 212],
            ["name" => "Szudán", "code" => "SD", "sort_order" => 213],
            ["name" => "Szváziföld", "code" => "SZ", "sort_order" => 214],
            ["name" => "Tádzsikisztán", "code" => "TJ", "sort_order" => 215],
            ["name" => "Tajvan", "code" => "TW", "sort_order" => 216],
            ["name" => "Tanzánia", "code" => "TZ", "sort_order" => 217],
            ["name" => "Thaiföld", "code" => "TH", "sort_order" => 218],
            ["name" => "Togo", "code" => "TG", "sort_order" => 219],
            ["name" => "Tokelau", "code" => "TK", "sort_order" => 220],
            ["name" => "Tonga", "code" => "TO", "sort_order" => 221],
            ["name" => "Törökország", "code" => "TR", "sort_order" => 222],
            ["name" => "Trinidad és Tobago", "code" => "TT", "sort_order" => 223],
            ["name" => "Tunézia", "code" => "TN", "sort_order" => 224],
            ["name" => "Turks- és Caicos-szigetek", "code" => "TC", "sort_order" => 225],
            ["name" => "Tuvalu", "code" => "TV", "sort_order" => 226],
            ["name" => "Türkmenisztán", "code" => "TM", "sort_order" => 227],
            ["name" => "Uganda", "code" => "UG", "sort_order" => 228],
            ["name" => "Új-Kaledónia", "code" => "NC", "sort_order" => 229],
            ["name" => "Új-Zéland", "code" => "NZ", "sort_order" => 230],
            ["name" => "Ukrajna", "code" => "UA", "sort_order" => 231],
            ["name" => "Uruguay", "code" => "UY", "sort_order" => 232],
            ["name" => "Üzbegisztán", "code" => "UZ", "sort_order" => 233],
            ["name" => "Vanuatu", "code" => "VU", "sort_order" => 234],
            ["name" => "Vatikán", "code" => "VA", "sort_order" => 235],
            ["name" => "Venezuela", "code" => "VE", "sort_order" => 236],
            ["name" => "Vietnám", "code" => "VN", "sort_order" => 237],
            ["name" => "Wallis és Futuna", "code" => "WF", "sort_order" => 238],
            ["name" => "Zambia", "code" => "ZM", "sort_order" => 239],
            ["name" => "Zimbabwe", "code" => "ZW", "sort_order" => 240],
            ["name" => "Zöld-foki Köztársaság", "code" => "CV", "sort_order" => 241],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['code' => $country['code']], $country);
        }
    }
}
